apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecretName }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Values.externalSecretSecretStoreRefName }}
    kind: {{ .Values.externalSecretSecretStoreRefKind | default "ClusterSecretStore" }}
  target:
    name: {{ .Values.externalSecretName }}
    creationPolicy: Owner
  data:
  - secretKey: {{ .Values.externalSecretSecretKey | default "github_token" }}
    remoteRef:
      key: {{ .Values.externalSecretRemoteRefKey }}
      property: {{ .Values.externalSecretRemoteRefProperty }}
